PARSING_TABLE = [
["program","id",";",".","array","[","num","..","]","of","integer","real","function",":","procedure","l#","r#","begin","end","if","then","while","do","else","not","+","-",",","var","*","/","div","mod","and","=",">","<","<=",">=","<>","or",":=","$"]
,
[1,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",2,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR",4,"ERROR","ERROR","ERROR","ERROR","ERROR",3,3,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",5,6,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",7,"ERROR",7,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",8,"ERROR",8,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",9,"ERROR",10,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",12,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",12,"ERROR",11,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",13,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",14,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",15,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",15,16,15,"ERROR",15,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",17,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",17,"ERROR",17,"ERROR",17,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",19,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",20,"ERROR",21,"ERROR",22,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",24,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",24,"ERROR","ERROR","ERROR","ERROR",24,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",25,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR",26,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",27,"ERROR"]
,["ERROR",28,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",30,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",29,"ERROR","ERROR",30,"ERROR","ERROR","ERROR","ERROR",30,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",31,"ERROR","ERROR","ERROR","ERROR",31,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",31,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",31,31,31,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",32,"ERROR","ERROR","ERROR","ERROR",32,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",32,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",32,32,32,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",34,"ERROR","ERROR","ERROR","ERROR","ERROR",34,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",34,"ERROR",34,"ERROR",34,"ERROR",34,34,"ERROR","ERROR","ERROR",34,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",33,33,33,33,33,33,"ERROR","ERROR","ERROR"]
,["ERROR",35,"ERROR","ERROR","ERROR","ERROR",35,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",35,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",35,36,36,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",37,"ERROR","ERROR","ERROR","ERROR",37,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",37,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",37,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",39,"ERROR","ERROR","ERROR","ERROR","ERROR",39,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",38,39,"ERROR",39,"ERROR",39,"ERROR",39,39,"ERROR",39,39,39,"ERROR",39,39,39,39,39,39,39,39,39,39,39,39,"ERROR","ERROR"]
,["ERROR",40,"ERROR","ERROR","ERROR","ERROR",41,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",42,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",43,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",44,45,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",47,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",46,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",48,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",50,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",50,"ERROR",50,"ERROR","ERROR",50,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",49,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",51,"ERROR",51,"ERROR","ERROR",52,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",53,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",54,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",55,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",56,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",58,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",57,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",60,"ERROR","ERROR","ERROR","ERROR","ERROR",60,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",60,"ERROR",60,"ERROR",60,"ERROR",60,60,"ERROR",59,59,60,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",60,60,60,60,60,60,59,"ERROR","ERROR"]
,["ERROR","ERROR",62,"ERROR","ERROR","ERROR","ERROR","ERROR",62,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",62,"ERROR",62,"ERROR",62,"ERROR",62,62,"ERROR",62,62,62,"ERROR",61,61,61,61,61,62,62,62,62,62,62,62,"ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",63,64,65,66,67,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",68,69,70,71,72,73,"ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",74,75,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",76,"ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",77,"ERROR"]
]

production_mapping = {
    "1" :[header, 1],
    "2" :[identifier_list, 1],
    "3" :[type_, 1],
    "4" :[type_, 2],
    "5" :[standard_type, 1],
    "6" :[standard_type, 2],
    "7" :[subprogram_declarations, 1],
    "8" :[subprogram_declarations, 2],
    "9" :[subprogram_head, 1],
    "10" :[subprogram_head, 2],
    "11" :[args, 1],
    "12" :[args, 2],
    "13" :[parameter_list, 1],
    "14" :[compound_statement, 1],
    "15" :[optional_statements, 1],
    "16" :[optional_statements, 2],
    "17" :[statement_list, 1],
    "18" :[statement, 1],
    "19" :[statement, 2],
    "20" :[statement, 3],
    "21" :[statement, 4],
    "22" :[statement, 5],
    "23" :[match_statement, 1],
    "24" :[match_statement, 2],
    "25" :[variable, 1],
    "26" :[variable, 2],
    "27" :[variable, 3],
    "28" :[procedure_statement, 1],
    "29" :[procedure_statement, 2],
    "30" :[procedure_statement, 3],
    "31" :[expression_list, 1],
    "32" :[expression, 1],
    "33" :[expression, 2],
    "34" :[expression, 3],
    "35" :[simple_expression, 1],
    "36" :[simple_expression, 2],
    "37" :[term, 1],
    "38" :[factor_, 1],
    "39" :[factor_, 2],
    "40" :[factor, 1],
    "41" :[factor, 2],
    "42" :[factor, 3],
    "43" :[factor, 4],
    "44" :[sign, 1],
    "45" :[sign, 2],
    "46" :[identifier_list_, 1],
    "47" :[identifier_list_, 2],
    "48" :[declarations, 1],
    "49" :[declarations, 2],
    "50" :[declarations, 3],
    "51" :[subprogram_declarations_, 1],
    "52" :[subprogram_declarations_, 2],
    "53" :[parameter_list_, 1],
    "54" :[parameter_list_, 2],
    "55" :[statement_list_, 1],
    "56" :[statement_list_, 2],
    "57" :[expression_list_, 1],
    "58" :[expression_list_, 2],
    "59" :[simple_expression_, 1],
    "60" :[simple_expression_, 2],
    "61" :[term_, 1],
    "62" :[term_, 2],
    "63" :[term_, 3],
    "64" :[mulop, 1],
    "65" :[mulop, 2],
    "66" :[mulop, 3],
    "67" :[mulop, 4]
    "68" :[relop, 1],
    "69" :[relop, 2],
    "70" :[relop, 3],
    "71" :[relop, 4],
    "72" :[relop, 5],
    "73" :[relop, 6],
    "74" :[addop, 1],
    "75" :[addop, 2],
    "76" :[addop, 3],
    "77" :[assignop, 1],

}