PARSING_TABLE = [
["program","id",";",".","array","[","num","..","]","of","integer","real","function",":","procedure","l#","r#","begin","end","if","then","while","do","else","not","+","-",",","var","*","/","div","mod","and","=",">","<","<=",">=","<>","or",":=","$"]
,
[1,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",2,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR",4,"ERROR","ERROR","ERROR","ERROR","ERROR",3,3,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",5,6,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",7,"ERROR",7,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",8,"ERROR",8,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",9,"ERROR",10,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",12,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",12,"ERROR",11,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",13,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",14,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",15,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",15,16,15,"ERROR",15,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",17,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",17,"ERROR",17,"ERROR",17,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",19,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",20,"ERROR",21,"ERROR",22,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",24,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",24,"ERROR","ERROR","ERROR","ERROR",24,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",25,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR",26,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",27,"ERROR"]
,["ERROR",28,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",30,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",29,"ERROR","ERROR",30,"ERROR","ERROR","ERROR","ERROR",30,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",31,"ERROR","ERROR","ERROR","ERROR",31,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",31,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",31,31,31,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",32,"ERROR","ERROR","ERROR","ERROR",32,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",32,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",32,32,32,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",34,"ERROR","ERROR","ERROR","ERROR","ERROR",34,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",34,"ERROR",34,"ERROR",34,"ERROR",34,34,"ERROR","ERROR","ERROR",34,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",33,33,33,33,33,33,"ERROR","ERROR","ERROR"]
,["ERROR",35,"ERROR","ERROR","ERROR","ERROR",35,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",35,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",35,36,36,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR",37,"ERROR","ERROR","ERROR","ERROR",37,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",37,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",37,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",39,"ERROR","ERROR","ERROR","ERROR","ERROR",39,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",38,39,"ERROR",39,"ERROR",39,"ERROR",39,39,"ERROR",39,39,39,"ERROR",39,39,39,39,39,39,39,39,39,39,39,39,"ERROR","ERROR"]
,["ERROR",40,"ERROR","ERROR","ERROR","ERROR",41,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",42,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",43,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",44,45,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",47,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",46,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",48,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",50,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",50,"ERROR",50,"ERROR","ERROR",50,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",49,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",51,"ERROR",51,"ERROR","ERROR",52,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",53,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",54,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",55,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",56,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",58,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",57,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR",60,"ERROR","ERROR","ERROR","ERROR","ERROR",60,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",60,"ERROR",60,"ERROR",60,"ERROR",60,60,"ERROR",59,59,60,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",60,60,60,60,60,60,59,"ERROR","ERROR"]
,["ERROR","ERROR",62,"ERROR","ERROR","ERROR","ERROR","ERROR",62,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",62,"ERROR",62,"ERROR",62,"ERROR",62,62,"ERROR",62,62,62,"ERROR",61,61,61,61,61,62,62,62,62,62,62,62,"ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",63,64,65,66,67,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",68,69,70,71,72,73,"ERROR","ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",74,75,"ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",76,"ERROR","ERROR"]
,["ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR","ERROR",77,"ERROR"]
]

production_mapping = {
    "1" :header,
    "2" :identifier_list,
    "3" :type_,
    "4" :type_,
    "5" :standard_type,
    "6" :standard_type,
    "7" :subprogram_declarations,
    "8" :subprogram_declarations,
    "9" :subprogram_head,
    "10" :subprogram_head,
    "11" :args,
    "12" :args,
    "13" :parameter_list,
    "14" :compound_statement,
    "15" :optional_statements,
    "16" :optional_statements,
    "17" :statement_list,
    "18" :statement,
    "19" :statement,
    "20" :statement,
    "21" :statement,
    "22" :statement,
    "23" :match_statement,
    "24" :match_statement,
    "25" :variable,
    "26" :variable,
    "27" :variable,
    "28" :procedure_statement,
    "29" :procedure_statement,
    "30" :procedure_statement,
    "31" :expression_list,
    "32" :expression,
    "33" :expression,
    "34" :expression,
    "35" :simple_expression,
    "36" :simple_expression,
    "37" :term,
    "38" :factor_,
    "39" :factor_,
    "40" :factor,
    "41" :factor,
    "42" :factor,
    "43" :factor,
    "44" :sign,
    "45" :sign,
    "46" :identifier_list_,
    "47" :identifier_list_,
    "48" :declarations,
    "49" :declarations,
    "50" :declarations,
    "51" :subprogram_declarations_,
    "52" :subprogram_declarations_,
    "53" :parameter_list_,
    "54" :parameter_list_,
    "55" :statement_list_,
    "56" :statement_list_,
    "57" :expression_list_,
    "58" :expression_list_,
    "59" :simple_expression_,
    "60" :simple_expression_,
    "61" :term_,
    "62" :term_,
    "63" :term_,
    "64" :mulop,
    "65" :mulop,
    "66" :mulop,
    "67" :mulop,
    "68" :relop,
    "69" :relop,
    "70" :relop,
    "71" :relop,
    "72" :relop,
    "73" :relop,
    "74" :addop,
    "75" :addop,
    "76" :addop,
    "77" :assignop,

}